import React from 'react';
import { X, Printer, Download, ShieldCheck, ShieldAlert, FileText, CheckCircle2 } from 'lucide-react';

export default function SecurityReportModal({ scenario, onClose }) {
  if (!scenario) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#0e131d] border border-slate-700/80 rounded-2xl w-full max-w-4xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="p-5 border-b border-slate-800 bg-[#141b27] flex items-center justify-between print:hidden">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-blue-950 border border-blue-500/40 rounded-xl text-blue-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-100">
                Executive Cybersecurity Audit Report
              </h2>
              <p className="text-xs text-slate-400">
                Cloud IAM Risk Analysis & AI Remediation Assessment
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg border border-slate-700 flex items-center gap-1.5 transition"
            >
              <Printer className="w-4 h-4 text-cyan-400" />
              <span>Print / Save PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-1 hover:bg-slate-800 text-slate-400 hover:text-slate-100 rounded transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Document Content */}
        <div className="p-8 space-y-6 overflow-y-auto bg-[#0b0e15] text-slate-200 text-xs font-sans print:bg-white print:text-black">
          {/* Document Header */}
          <div className="border-b border-slate-800 pb-5 flex items-start justify-between">
            <div>
              <div className="text-xs font-bold text-cyan-400 uppercase tracking-widest mb-1">
                CONFIDENTIAL • CYBERSECURITY AUDIT REPORT
              </div>
              <h1 className="text-xl font-black text-slate-100">
                {scenario.title}
              </h1>
              <p className="text-xs text-slate-400 mt-1">
                Generated by AI Cloud Permission Risk Visualizer Engine v2.0 • Date: {new Date().toLocaleDateString()}
              </p>
            </div>

            <div className="text-right">
              <div className="text-xs text-slate-400">Environment Posture Score</div>
              <div className={`text-2xl font-black font-mono mt-0.5 ${
                scenario.overallRiskScore >= 80 ? 'text-red-400' :
                scenario.overallRiskScore >= 60 ? 'text-amber-400' : 'text-emerald-400'
              }`}>
                {scenario.overallRiskScore} / 100
              </div>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
              1. Executive Summary
            </h3>
            <p className="text-xs text-slate-300 leading-relaxed bg-[#111723] p-4 rounded-xl border border-slate-800">
              {scenario.description}
            </p>
          </div>

          {/* Compliance Matrix */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
              2. Regulatory & Compliance Evaluation
            </h3>
            <div className="grid grid-cols-3 gap-3">
              <div className="p-3 bg-[#111723] border border-slate-800 rounded-xl">
                <div className="text-xs font-bold text-slate-300">SOC 2 Type II</div>
                <div className="text-[11px] text-red-400 mt-1 flex items-center gap-1 font-semibold">
                  <ShieldAlert className="w-3.5 h-3.5" />
                  <span>NON-COMPLIANT (Access Control)</span>
                </div>
              </div>

              <div className="p-3 bg-[#111723] border border-slate-800 rounded-xl">
                <div className="text-xs font-bold text-slate-300">ISO/IEC 27001</div>
                <div className="text-[11px] text-amber-400 mt-1 flex items-center gap-1 font-semibold">
                  <ShieldAlert className="w-3.5 h-3.5" />
                  <span>ACTION REQUIRED (A.9.2.6)</span>
                </div>
              </div>

              <div className="p-3 bg-[#111723] border border-slate-800 rounded-xl">
                <div className="text-xs font-bold text-slate-300">CIS Cloud Benchmark</div>
                <div className="text-[11px] text-red-400 mt-1 flex items-center gap-1 font-semibold">
                  <ShieldAlert className="w-3.5 h-3.5" />
                  <span>3 Critical Findings</span>
                </div>
              </div>
            </div>
          </div>

          {/* Identified Attack Paths */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
              3. Critical Attack Path Sequence
            </h3>
            <div className="bg-[#111723] border border-slate-800 rounded-xl p-4 space-y-3">
              {scenario.attackNarrative?.map((item, idx) => (
                <div key={idx} className="flex items-start gap-3 border-b border-slate-800/80 pb-2.5 last:border-none">
                  <span className="px-2 py-0.5 bg-red-950 border border-red-500/30 text-red-400 text-[10px] font-bold rounded">
                    Step {idx + 1}
                  </span>
                  <div>
                    <div className="text-xs font-bold text-slate-200">{item.title}</div>
                    <div className="text-xs text-slate-400 mt-0.5">{item.description}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Inventory Table */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
              4. IAM Permissions Inventory & Risk Breakdown
            </h3>
            <table className="w-full text-left border-collapse border border-slate-800 rounded-xl overflow-hidden">
              <thead className="bg-[#172030] text-slate-300 font-semibold text-[11px]">
                <tr>
                  <th className="p-2.5">Node Name</th>
                  <th className="p-2.5">Category</th>
                  <th className="p-2.5">Cloud</th>
                  <th className="p-2.5">Risk Score</th>
                  <th className="p-2.5">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 text-xs">
                {scenario.nodes.map((node) => (
                  <tr key={node.id} className="hover:bg-slate-900/50">
                    <td className="p-2.5 font-medium text-slate-200">{node.label}</td>
                    <td className="p-2.5 text-slate-400">{node.category}</td>
                    <td className="p-2.5 text-slate-400">{node.cloudProvider}</td>
                    <td className="p-2.5 font-mono font-bold">
                      <span className={node.riskLevel === 'critical' ? 'text-red-400' : node.riskLevel === 'high' ? 'text-amber-400' : 'text-emerald-400'}>
                        {node.riskScore}/100
                      </span>
                    </td>
                    <td className="p-2.5 font-semibold">
                      {node.remediated ? (
                        <span className="text-emerald-400 flex items-center gap-1">
                          <CheckCircle2 className="w-3.5 h-3.5" /> Remediated
                        </span>
                      ) : (
                        <span className="text-red-400 uppercase text-[10px]">{node.riskLevel}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
